name: AWAtv
options:
  bundleIdPrefix: com.awatv
  createIntermediateGroups: true
  deploymentTarget:
    tvOS: "17.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.2.1"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_STRICT_CONCURRENCY: minimal
    CLANG_ENABLE_MODULES: YES
    SWIFT_EMIT_LOC_STRINGS: YES

targets:
  AWAtv:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/AWAtv
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Resources/Assets.xcassets
    info:
      path: Resources/Info.plist
      properties:
        CFBundleName: AWAtv
        CFBundleDisplayName: AWAtv
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: APPL
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        LSRequiresIPhoneOS: false
        UIDeviceFamily: [3]
        UIRequiredDeviceCapabilities: [arm64]
        UIUserInterfaceStyle: Dark
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsLocalNetworking: true
        TVTopShelfImage: $(PRODUCT_NAME)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.awatv.appletv
        PRODUCT_NAME: AWAtv
        TARGETED_DEVICE_FAMILY: "3"
        SUPPORTED_PLATFORMS: "appletvos appletvsimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon &amp; Top Shelf Image"
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: LaunchImage
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        TVOS_DEPLOYMENT_TARGET: "17.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

schemes:
  AWAtv:
    build:
      targets:
        AWAtv: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
